// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDePiBfTLgVCwpubSj0UgIG_kTlv11KaqA',
    appId: '1:416115488340:web:ced51643cc030aed3e9fc1',
    messagingSenderId: '416115488340',
    projectId: 'calaton-auth',
    authDomain: 'calaton-auth.firebaseapp.com',
    storageBucket: 'calaton-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMXjaxDejMqIE2OM-9o3VEzJJGRRMKXDc',
    appId: '1:416115488340:android:fba90c99069384f63e9fc1',
    messagingSenderId: '416115488340',
    projectId: 'calaton-auth',
    storageBucket: 'calaton-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw2ZqiJWiu7JqC70TcxxzRrXSVPj53Iyc',
    appId: '1:416115488340:ios:3c8fd55202b9c7f83e9fc1',
    messagingSenderId: '416115488340',
    projectId: 'calaton-auth',
    storageBucket: 'calaton-auth.appspot.com',
    iosBundleId: 'com.example.calatonFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw2ZqiJWiu7JqC70TcxxzRrXSVPj53Iyc',
    appId: '1:416115488340:ios:761883fe1a5490b23e9fc1',
    messagingSenderId: '416115488340',
    projectId: 'calaton-auth',
    storageBucket: 'calaton-auth.appspot.com',
    iosBundleId: 'com.example.calatonFirebaseAuth.RunnerTests',
  );
}
